apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: geth-ministerio
  namespace: ministerio
spec:
  serviceName: geth-ministerio
  replicas: 1
  selector:
    matchLabels:
      app: geth-ministerio
  template:
    metadata:
      labels:
        app: geth-ministerio
    spec:
      containers:
        - name: geth
          image: ethereum/client-go:v1.13.15
          ports:
            - containerPort: 8545
            - containerPort: 30303
          env:
            - name: PRIVATE_KEY_GETH
              value: "6cbed15c793ce57650b9877cf6fa156fbef513c4e6134f022a85b1ffdd59b2a1"
          command:
            - /bin/sh
            - -c
            - |
              if [ ! -d /data/geth/chaindata ]; then geth --datadir /data init /config/genesis.json; fi
              printf "%s" "$PRIVATE_KEY_GETH" > /tmp/privatekey
              : > /tmp/password
              geth --datadir /data account import --password /tmp/password /tmp/privatekey || true
              cp /config/static-nodes.json /data/geth/static-nodes.json
              exec geth --datadir /data --networkid 202606 --syncmode full --http --http.addr 0.0.0.0 --http.port 8545 --http.api eth,net,web3,admin,personal,miner,clique --http.vhosts "*" --http.corsdomain "*" --port 30303 --mine --miner.etherbase 0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0 --unlock 0xFFcf8FDEE72ac11b5c542428B35EEF5769C409f0 --password /tmp/password --allow-insecure-unlock
          volumeMounts:
            - name: geth-data
              mountPath: /data
            - name: geth-config
              mountPath: /config
      volumes:
        - name: geth-data
          persistentVolumeClaim:
            claimName: geth-ministerio-data
        - name: geth-config
          configMap:
            name: geth-ministerio-config
