apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-utpl-data
  namespace: blockchain-forense
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-ministerio-data
  namespace: blockchain-forense
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-auditora-data
  namespace: blockchain-forense
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
