apiVersion: v1
kind: Secret
metadata:
  name: api-universidad-secret
  namespace: utpl
type: Opaque
stringData:
  POSTGRES_DB: titulos_db
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin123
  UNIVERSIDAD_PRIVATE_KEY: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
  GANACHE_PRIVATE_KEY: "0x4f3edf983ac636a65a842ce7c78d9aa706d3b113bce9c46f30d7d21715b23b1d"
