apiVersion: v1
kind: ConfigMap
metadata:
  name: api-auditora-config
  namespace: auditora
data:
  BLOCKCHAIN_RPC_URL: http://geth-auditora:8545
  CONTRACT_ADDRESS: "0xREEMPLAZAR_CON_DIRECCION_DEL_CONTRATO"
