apiVersion: v1
kind: Secret
metadata:
  name: api-auditora-secret
  namespace: auditora
type: Opaque
stringData:
  POSTGRES_AUDITORA_DB: auditora_db
  POSTGRES_AUDITORA_USER: auditora
  POSTGRES_AUDITORA_PASSWORD: auditora123
